* lein-runit

A Leiningen plugin that makes easy to deploy production code with the [[http://smarden.org/runit/][runit]] supervisor.
If you’ve never used runit before, you may want to refer to Kevin Chard’s excellent [[http://kchard.github.io/runit-quickstart/][quickstart]]. I have curated some more links in a blog [[http://danielsz.github.io/2014/12/06/lein-runit/][post]]. Once you understand how things work, you may want to come back and use *lein-runit* to automate the workflow for Clojure projects.

** Installation

Put the following into the *:plugins* vector in either *project.clj* or *~/.lein/profiles.clj*.

#+BEGIN_SRC clojure
[org.danielsz/lein-runit "0.1.0-SNAPSHOT"]
#+END_SRC

** Usage

Define a *:runit* vector in your project.clj with the paths to your application root and service root paths. On debian, for example:

#+BEGIN_SRC clojure
:runit {:app-root "/opt"
        :service-root "/etc/sv"}
#+END_SRC

Since this plugin makes sense for production scenarii, this is most likely what you’ll want to issue at the command line:

#+BEGIN_SRC sh
$ lein with-profile production runit
#+END_SRC

Finally, change to the target directory, and run the shell script that will move everything into place with the right permissions:

#+BEGIN_SRC sh
$ cd target
$ ./commit.sh
#+END_SRC

*** Assumptions

The assumptions made by *lein-runit* are that:

- You are using the [[https://github.com/weavejester/environ][environ]] library to set the environment variables for your project.
- You are deploying an uberjar. (*lein with-profile production uberjar*)

** License

Copyright © 2014 Daniel Szmulewicz

Distributed under the Eclipse Public License.
